undercloud_generate_service_certificate: false
undercloud_clean_nodes: true
ssl_overcloud: false
step_introspect: false
containerized_overcloud: true
containerized_undercloud: true
containerized_overcloud_upgrade: true
enable_pacemaker: true

undercloud_enable_ui: false

telemetry_args: >-
   -e {{ overcloud_templates_path }}/environments/disable-telemetry.yaml

extra_args: >-
  --ntp-server pool.ntp.org
  -e {{ overcloud_templates_path }}/environments/ceph-ansible/ceph-ansible.yaml
test_ping: true
modify_image_vc_verbose: true
modify_image_vc_root_password: abc123

# Use local mirror for images
#overcloud_image_url: http://192.168.122.1/pub/queens-tripleo/overcloud-full.tar
#ipa_image_url: http://192.168.122.1/pub/queens-tripleo/ironic-python-agent.tar
#undercloud_image_url: http://192.168.122.1/pub/queens-tripleo/undercloud.qcow2

undercloud_network_cidr: 192.168.24.0/24
#undercloud_network_gateway: 192.168.24.1
#undercloud_undercloud_public_vip: 192.168.24.2
#undercloud_undercloud_admin_vip: 192.168.24.3
#undercloud_local_interface: eth1
#undercloud_masquerade_network: 192.168.24.0/24
#undercloud_dhcp_start: 192.168.24.5
#undercloud_dhcp_end: 192.168.24.24
#undercloud_inspection_iprange: 192.168.24.25,192.168.24.39
#undercloud_external_network_cidr: 10.0.0.0/24

overcloud_dns_servers: ["208.67.222.123", "208.67.220.123"]
network_environment_args:
  ExternalNetCidr: "{{ undercloud_external_network_cidr }}"
  ExternalAllocationPools: >
    [{'start': '{{ undercloud_external_network_cidr|nthhost(10) }}',
    'end': '{{ undercloud_external_network_cidr|nthhost(50) }}'}]
  NeutronExternalNetworkBridge: ""
  ControlPlaneSubnetCidr: "{{ undercloud_network_cidr|ipaddr('prefix') }}"
  ControlPlaneDefaultRoute: "{{ undercloud_network_cidr|nthhost(1) }}"
  EC2MetadataIp: "{{ undercloud_network_cidr|nthhost(1) }}"
  ExternalInterfaceDefaultRoute: "{{ undercloud_external_network_cidr|nthhost(1) }}"
  InternalApiNetCidr: 172.20.0.0/24
  InternalApiAllocationPools: [{"start": "172.20.0.10", "end": "172.20.0.250"}]
  StorageNetCidr: 172.18.0.0/24
  StorageAllocationPools: [{"start": "172.18.0.10", "end": "172.18.0.250"}]
  StorageMgmtNetCidr: 172.19.0.0/24
  StorageMgmtAllocationPools: [{"start": "172.19.0.10", "end": "172.19.0.250"}]
  TenantNetCidr: 172.16.0.0/24
  TenantAllocationPools: [{"start": "172.16.0.10", "end": "172.16.0.250"}]
  DnsServers: "{{ overcloud_dns_servers }}"
  PublicVirtualFixedIPs: [{ "ip_address": "{{ undercloud_external_network_cidr|nthhost(5) }}" }]

network_isolation: true
network_isolation_type: 'single-nic-vlans'
topology: >-
  --compute-scale 1
  --control-scale 3
  --ceph-storage-scale 3
