undercloud_memory: 32768 # 12288
undercloud_vcpu: 8 # 4

control_memory: 8192 # 8192
control_vcpu: 2 # 2

compute_memory: 8192 # 8192
compute_vcpu: 2 # 2

ceph_memory: 8192 # 8192
ceph_vcpu: 2 # 2

overcloud_nodes:
  - name: control_0
    flavor: control
    virtualbmc_port: 6230

  - name: control_1
    flavor: control
    virtualbmc_port: 6231

  - name: control_2
    flavor: control
    virtualbmc_port: 6232

  - name: compute_0
    flavor: compute
    virtualbmc_port: 6233

  - name: ceph_0
    flavor: ceph
    virtualbmc_port: 6234

  - name: ceph_1
    flavor: ceph
    virtualbmc_port: 6235

  - name: ceph_2
    flavor: ceph
    virtualbmc_port: 6236

topology: >-
  --control-scale 1
  --compute-scale 1
  --ceph-storage-scale 1

extra_args: >-
  --libvirt-type qemu
  -e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-ansible.yaml

undercloud_enable_telemetry: false
undercloud_enable_ui: false

extradisks_list:
  - vdb
  - vdc
  - vdd
  - vde
  - vdf
  - vdg
  - vdh
  - vdi
  - vdl
  - vdm
  - vdn
  - vdo
  - vdp
  - vdq
  - vdr
  - vds
  - vdt
  - vdu
  - vdv
  - vdz
